services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app # Mount local files for development
      - /app/node_modules # Prevent conflicts
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0